apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mtls-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '3.6'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          clientId: kafka-broker-service-account
          clientSecret:
            key: clientSecret
            secretName: kafka-broker-service-account
          introspectionEndpointUri: 'https://keycloak-keycloak.apps.cluster-psfnh.dynamic.redhatworkshops.io/auth/realms/kafka-authz/protocol/openid-connect/token/introspect'
          maxSecondsWithoutReauthentication: 3600
          type: oauth
          userNameClaim: preferred_username
          validIssuerUri: 'https://keycloak-keycloak.apps.cluster-psfnh.dynamic.redhatworkshops.io/auth/realms/kafka-authz'
        name: external
        port: 9094
        tls: true
        type: route
    replicas: 3
    storage:
      type: ephemeral
    version: 3.6.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
